name: branch-preview

on:
  pull_request:
    paths:
      - ".github/workflows/branch-preview.yml"
      - "**.js"
      - "**.jsx"
      - "src/**"
      - "package.json"
      - "yarn.lock"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Expo CLI
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_ACCESS_TOKEN }}

      # Cache the node_modules directory
      - name: Set up node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/yarn.lock') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Recreate staging .env file
        run: echo "GOOGLE_CLIENT_ID=${{ secrets.STAGING_GOOGLE_CLIENT_ID }}" > .env

      - name: Publish preview with Expo
        run: expo publish --non-interactive --release-channel pr-${{ github.event.number }}-preview

      - name: Add comment with QR to the Pull Request
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          EXPO_PROJECT: "@proyectoespecialidad/capstone"
        with:
          message: |
            # Branch preview:

            ![Expo QR](https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=exp://exp.host/${{ env.EXPO_PROJECT }}?release-channel=pr-${{ github.event.number }}-preview)

            Published to https://exp.host/${{ env.EXPO_PROJECT }}?release-channel=pr-${{ github.event.number }}-preview.
